# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 3.0.0.0rc2.dev10\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: nova_powervm/virt/powervm/driver.py:1548
msgid "Live migration timed out. Aborting migration"
msgstr "La migración en directo ha excedido el tiempo de espera. Se aborta la migración"

#: nova_powervm/virt/powervm/live_migration.py:331
msgid "Live migration failed."
msgstr "La migración en directo ha fallado."

#: nova_powervm/virt/powervm/live_migration.py:385
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "La recuperación de la migración ha fallado con el error: %s"

#: nova_powervm/virt/powervm/live_migration.py:413
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"La terminación anormal de la migración en directo ha fallado. No es de bloqueo. La excepción se "
"registra a continuación."

#: nova_powervm/virt/powervm/vif.py:106
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "El suceso VIF personalizado ha fallado.  %s"

#: nova_powervm/virt/powervm/vif.py:316
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "No se puede desconectar VIF con mac %(mac)s para la instancia %(inst)s."

#: nova_powervm/virt/powervm/vm.py:646
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Ha fallado la supresión de la máquina virtual: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:258
#, python-format
msgid "Disk %s not found during resize."
msgstr "El disco %s no se ha encontrado durante el redimensionamiento."

#: nova_powervm/virt/powervm/disk/ssp.py:331
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Error al comprobar el almacenamiento compartido. excepción=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "No se ha podido actualizar la NVRAM: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"No se pueden eliminar los VIF de la instancia %(inst)s porque el sistema no tiene el "
"estado correcto.  El motivo notificado por el sistema es: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"No se pueden crear VIF para la instancia %(sys)s.  La máquina virtual estaba en un estado en el que "
"la conexión VIF no se podía aceptar.  El motivo del sistema es: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Error al esperar a que se creara el VIF para la instancia %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Anomalía de la conexión VIF para la devolución de llamada en el evento %(event)s para la instancia %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "No se ha podido almacenar la NVRAM para la instancia %(name)s. Excepción: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "No se ha podido suprimir la NVRAM para la instancia %(name)s. Excepción: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:221
#: nova_powervm/virt/powervm/volume/vscsi.py:334
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "No se puede desconectar volúmenes de la máquina virtual: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:223
#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid "Error: %s"
msgstr "Error: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:515
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Las correlaciones no han podido encontrar un servidor de E/S virtual apropiado. Las correlaciones de puertos eran %s."

# ENGL1SH_VERS10N 37135_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV132AAP001 2
